url: 'https://willcb.com'
include: [CNAME]
baseurl: ''
title: 'William Brown'

plugins:
  - jekyll-postcss

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
  auto_ids: true
  toc_levels: 1..3
social:
  twitter: willccbb
  linkedin: willcb
  scholar: JUJdJMoAAAAJ
  github: willccbb
  email: w.brown@columbia.edu

permalink: /blog/:title/

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
