url: 'https://willccbb.github.io'
baseurl: ''
title: 'William Brown'

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
